module.exports.authService = require('./auth.service')
module.exports.taskService = require('./task.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.payslipService = require('./payslip.service')
module.exports.leaveService = require('./leave.service')
