module.exports.authController = require('./auth.controller')
module.exports.taskController = require('./task.controller')
module.exports.statusController = require('./status.controller')
module.exports.payslipController = require('./payslip.controller')
module.exports.leaveController = require('./leave.controller')
